// Code generated by go_code.py; DO NOT EDIT.

package utils
var KnownTextualMimes = map[string]bool{
  "application/x-sh": true,
  "application/x-csh": true,
  "application/x-shellscript": true,
  "application/javascript": true,
  "application/json": true,
  "application/xml": true,
  "application/x-yaml": true,
  "application/yaml": true,
  "application/x-toml": true,
  "application/x-lua": true,
  "application/toml": true,
  "application/rss+xml": true,
  "application/xhtml+xml": true,
  "application/x-tex": true,
  "application/x-latex": true,
}
var KnownExtensions = map[string]string{
  ".asciidoc": "text/asciidoctor",
  ".conf": "text/config",
  ".md": "text/markdown",
  ".pyj": "text/rapydscript-ng",
  ".recipe": "text/python",
  ".rst": "text/restructured-text",
  ".rb": "text/ruby",
  ".toml": "text/toml",
  ".vim": "text/vim",
  ".yaml": "text/yaml",
  ".js": "text/javascript",
  ".json": "text/json",
}

